### ISSUE TITLE
🐛 Error when creating ARGO program in ARGO Platform

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/program-service#362]
## Describe the bug
Error when creating an ARGO program in 'Program Services' in ARGO Platform (https://platform.icgc-argo.org/submission/program/create).

## Steps To Reproduce
Go to https://platform.icgc-argo.org/submission/program/create and create program PPANC-GB
When you click on "Create", a pop-up message appears with the following error message: `Something went wrong, please try again later or contact us for assistance.`

![create_program_error](https://user-images.githubusercontent.com/4992044/137212163-8874e216-bc42-4c53-a8f6-6b1882fa2bba.png)

Detailed Error message in `Network` (right-click on "Inspect" -> select "Network" tab):

```
{
    "data": {
        "newProgram": null
    },
    "errors": [
        {
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "stacktrace": [
                        "Error: Error: 13 INTERNAL: {\"timestamp\":\"2021-10-05T19:02:14.302+0000\",\"status\":405,\"error\":\"Method Not Allowed\",\"message\":\"Request method 'POST' not supported\",\"path\":\"/users\"}",
                        "    at /appDir/dist/schemas/Program/index.js:347:27",
                        "    at Generator.throw (<anonymous>)",
                        "    at rejected (/appDir/dist/schemas/Program/index.js:24:65)",
                        "    at runMicrotasks (<anonymous>)",
                        "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
                    ]
                }
            },
            "locations": [],
            "message": "Error: 13 INTERNAL: {\"timestamp\":\"2021-10-05T19:02:14.302+0000\",\"status\":405,\"error\":\"Method Not Allowed\",\"message\":\"Request method 'POST' not supported\",\"path\":\"/users\"}",
            "path": [
                "createProgram"
            ]
        }
    ],
    "extensions": {
        "tracing": {
            "duration": 372584095,
            "endTime": "2021-10-05T19:02:14.317Z",
            "execution": {
                "resolvers": [
                    {
                        "duration": 370901072,
                        "fieldName": "createProgram",
                        "parentType": "Mutation",
                        "path": [
                            "newProgram"
                        ],
                        "returnType": "Program",
                        "startOffset": 1393871
                    }
                ]
            },
            "startTime": "2021-10-05T19:02:13.945Z",
            "version": 1
        }
    }
}
```

**Comment by hknahal** [comment]
@kcullion I tested it in QA using the same values I was trying in PROD and it created the program (PPANC-GB) successfully.

**Comment by kcullion** [comment]
Great thanks @hknahal and @blabadi ...I'll move this to awaiting release!

**Comment by kcullion** [comment]
Tested in Staging and I was able to make KIMC-CA program. @hknahal would you mind doing your test for PPANC-GB too in staging?

**Comment by hknahal** [comment]
@kcullion I was able to create the PPANC-GB program in Staging as well.

**Comment by kcullion** [comment]
Thanks @hknahal ..I'll move this to the next column, it's probably good to go to production!
